project_id = "vrxzwhbbblkqraimfclt"

[functions.db-upload-relay]
verify_jwt = true

[functions.process-docx]
# default verify_jwt is true; keeping explicit for clarity
verify_jwt = true

[functions.rag-generate]
verify_jwt = true

[functions.netdocs-auth-start]
verify_jwt = false

[functions.netdocs-auth-callback]
verify_jwt = false

[functions.netdocs-oauth]
verify_jwt = true

[functions.netdocs-search]
verify_jwt = true

