// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsitacetmjmojksaohnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzaXRhY2V0bWptb2prc2FvaG5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzE4MjcsImV4cCI6MjA2ODM0NzgyN30.cJ3X2SGpLzVyCt8LhAXJn3sT_FnhD-nypD5Xr4TRF-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});