// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrxzwhbbblkqraimfclt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyeHp3aGJiYmxrcXJhaW1mY2x0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMTE5OTgsImV4cCI6MjA2OTU4Nzk5OH0.xrJxNO2qOWV8lKP6uSUxTSD0BLc8AuQ6wqXH87VhLdo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});